llm: "openai"
model: "4o-mini"
chunking_strategy: "recursive_splitter"
input_url: "https://raw.githubusercontent.com/DataTalksClub/datatalksclub.github.io/refs/heads/main/_podcast/s01e05-mentoring.md"
